export { default as logo } from '../../Assets/img/logo.svg'
export { default as facebook } from '../../Assets/img/facebook (1) 1.svg'
export { default as instagramm } from '../../Assets/img/instagram (1) 1.svg'
export { default as twitter } from '../../Assets/img/twitter (1) 1.svg'
export { default as visa } from '../../Assets/img/visa-mastercard 1.svg'
